<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="NoSql" nsURI="http://www.nosql.com" nsPrefix="NoSql">
  <eClassifiers xsi:type="ecore:EClass" name="DO_DB">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="db_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" lowerBound="1"
        upperBound="-1" eType="#//Collection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="c_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        upperBound="-1" eType="#//Document" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="couple_D" lowerBound="1"
        upperBound="-1" eType="#//Couple" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Couple">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value_" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="couple_V" lowerBound="1"
        upperBound="-1" eType="#//Couple"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atomic" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//Atomic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value_Int" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//Atomic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value_Float" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Atomic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value_String" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Atomic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value_Bool" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
